use anyhow::{anyhow, bail, Result};
use std::collections::HashMap;
use std::time::Duration;

pub const DEFAULT_CATALYST: &str = "http://localhost:5141/content";
pub const UA: &str = "abgen/0.1";
const HTTP_TIMEOUT_SECS: u64 = 60;
const HTTP_RETRIES: u32 = 3;

#[derive(Clone, Debug)]
pub struct ContentEntry {
    pub file: String,
    pub hash: String,
}

/// Lowercased final path segments the upstream converter treats as
/// metadata-only regardless of how the entity references them
/// (`asset-reuse.ts::METADATA_ONLY_FILE_PATTERNS`).
const METADATA_ONLY_FILE_NAMES: [&str; 1] = ["autogenerated-thumbnail.png"];

/// Dot-paths into entity metadata whose string values name content files the
/// runtime reads as raw bytes only
/// (`asset-reuse.ts::METADATA_ONLY_METADATA_FIELDS`). Adding a field here
/// silently drops its target from every manifest, so only list fields the
/// client never imports as a bundle.
const METADATA_ONLY_METADATA_FIELDS: [&str; 1] = ["display.navmapThumbnail"];

fn read_by_path<'a>(v: &'a serde_json::Value, dot_path: &str) -> Option<&'a serde_json::Value> {
    let mut node = v;
    for key in dot_path.split('.') {
        node = node.get(key)?;
    }
    Some(node)
}

#[derive(Clone, Debug)]
pub struct Scene {
    pub entity_id: String,
    pub entity_type: String,
    pub pointers: Vec<String>,
    pub content: Vec<ContentEntry>,
    pub metadata: serde_json::Value,
}

impl Scene {
    pub fn content_by_file(&self) -> HashMap<String, String> {
        self.content
            .iter()
            .map(|c| (c.file.to_lowercase(), c.hash.clone()))
            .collect()
    }

    /// Hashes the upstream converter drops from Unity's input through
    /// `-skippedHashes`: display-only files the runtime fetches as raw bytes
    /// from the content server, so their bundles are never imported. Mirrors
    /// `asset-reuse.ts::findMetadataOnlyHashes` (file-pattern arm plus the
    /// `display.navmapThumbnail` metadata field, resolved case-insensitively).
    pub fn metadata_only_hashes(&self) -> std::collections::HashSet<String> {
        let mut hashes = std::collections::HashSet::new();
        let mut by_lower_file: HashMap<String, &str> = HashMap::with_capacity(self.content.len());
        for c in &self.content {
            let lf = c.file.to_lowercase();
            let last_segment = lf.rsplit('/').next().unwrap_or(lf.as_str());
            if METADATA_ONLY_FILE_NAMES.contains(&last_segment) {
                hashes.insert(c.hash.clone());
            }
            by_lower_file.insert(lf, c.hash.as_str());
        }
        for path in METADATA_ONLY_METADATA_FIELDS {
            let Some(value) = read_by_path(&self.metadata, path).and_then(|v| v.as_str()) else {
                continue;
            };
            if let Some(hash) = by_lower_file.get(value.to_lowercase().as_str()) {
                hashes.insert((*hash).to_string());
            }
        }
        hashes
    }

    pub fn files_with_ext(&self, exts: &[&str]) -> Vec<ContentEntry> {
        let lowered: Vec<String> = exts.iter().map(|e| e.to_lowercase()).collect();
        self.content
            .iter()
            .filter(|c| {
                let f = c.file.to_lowercase();
                lowered.iter().any(|e| f.ends_with(e.as_str()))
            })
            .cloned()
            .collect()
    }
}

fn is_pointer(target: &str) -> bool {
    let t = target.trim();
    if t.len() >= 4 && t[..4].eq_ignore_ascii_case("urn:") {
        return true;
    }
    let parts: Vec<&str> = t.split(',').collect();
    if parts.len() != 2 {
        return false;
    }
    parse_int_token(parts[0]) && parse_int_token(parts[1])
}

fn parse_int_token(s: &str) -> bool {
    let bytes = s.as_bytes();
    if bytes.is_empty() {
        return false;
    }
    let digits = if bytes[0] == b'-' { &bytes[1..] } else { bytes };
    !digits.is_empty() && digits.iter().all(|b| b.is_ascii_digit())
}

fn backoff(attempt: u32) -> Duration {
    Duration::from_secs_f64(0.5 * 2f64.powi(attempt as i32))
}

pub(crate) fn ensure_entity_id(v: &mut serde_json::Value, id: &str) {
    if v.get("id").and_then(|x| x.as_str()).is_none() {
        if let Some(obj) = v.as_object_mut() {
            obj.insert("id".to_string(), serde_json::Value::String(id.to_string()));
        }
    }
}

#[derive(Clone)]
pub struct CatalystClient {
    base: String,
    agent: ureq::Agent,
    local: Option<crate::local_store::LocalContentStore>,
    fallback_bases: Vec<String>,
}

impl CatalystClient {
    pub fn new(base_url: &str) -> Self {
        let per_host = crate::clihelp::default_network_concurrency();
        let agent: ureq::Agent = ureq::Agent::config_builder()
            .timeout_global(Some(Duration::from_secs(HTTP_TIMEOUT_SECS)))
            .max_redirects(0)
            .max_idle_connections_per_host(per_host)
            .max_idle_connections(2 * per_host)
            .max_idle_age(Duration::from_secs(60))
            .build()
            .into();
        CatalystClient {
            base: base_url.trim_end_matches('/').to_string(),
            agent,
            local: None,
            fallback_bases: Vec::new(),
        }
    }

    pub fn with_fallback_base(mut self, base: String) -> Self {
        self.fallback_bases
            .push(base.trim_end_matches('/').to_string());
        self
    }

    fn with_local_store(mut self, store: crate::local_store::LocalContentStore) -> Self {
        self.local = Some(store);
        self
    }

    pub fn from_args(catalyst: &str, local_root: Option<&str>) -> Self {
        let cli = Self::new(catalyst);
        match local_root {
            None => cli,
            Some(p) => {
                let root = if p.is_empty() {
                    crate::local_store::DEFAULT_CONTENT_ROOT
                } else {
                    p
                };
                eprintln!("--local: content fetches served from {root}");
                cli.with_local_store(crate::local_store::LocalContentStore::new(root))
            }
        }
    }

    fn get(&self, path: &str) -> Result<Vec<u8>> {
        self.get_abs(&format!("{}{}", self.base, path))
    }

    fn get_abs(&self, url: &str) -> Result<Vec<u8>> {
        let mut last: Option<String> = None;
        for attempt in 0..HTTP_RETRIES {
            match self.agent.get(url).header("User-Agent", UA).call() {
                Ok(resp) => {
                    let mut buf: Vec<u8> = Vec::new();
                    resp.into_body().into_reader().read_to_end(&mut buf)?;
                    return Ok(buf);
                }
                Err(ureq::Error::StatusCode(code)) => {
                    if code == 404 {
                        bail!("404 {}", url);
                    }
                    last = Some(format!("HTTP {code}"));
                }
                Err(e) => {
                    last = Some(e.to_string());
                }
            }
            std::thread::sleep(backoff(attempt));
        }
        bail!("GET {} failed: {}", url, last.unwrap_or_default())
    }

    fn post_json(&self, path: &str, body: &serde_json::Value) -> Result<Vec<u8>> {
        let url = format!("{}{}", self.base, path);
        let mut last: Option<String> = None;
        for attempt in 0..HTTP_RETRIES {
            match self
                .agent
                .post(&url)
                .header("User-Agent", UA)
                .header("Content-Type", "application/json")
                .send(body.to_string())
            {
                Ok(resp) => {
                    let mut buf: Vec<u8> = Vec::new();
                    resp.into_body().into_reader().read_to_end(&mut buf)?;
                    return Ok(buf);
                }
                Err(ureq::Error::StatusCode(code)) => {
                    last = Some(format!("HTTP {code}"));
                }
                Err(e) => {
                    last = Some(e.to_string());
                }
            }
            std::thread::sleep(backoff(attempt));
        }
        bail!("POST {} failed: {}", url, last.unwrap_or_default())
    }

    pub fn fetch_content(&self, content_hash: &str) -> Result<Vec<u8>> {
        let primary = if let Some(store) = &self.local {
            store
                .fetch(content_hash)
                .map_err(|e| anyhow!("local content store has no CID {content_hash}: {e}"))
        } else {
            self.get(&format!("/contents/{content_hash}"))
        };
        match primary {
            Ok(b) => Ok(b),
            Err(primary_err) => {
                for base in &self.fallback_bases {
                    if let Ok(b) = self.get_abs(&format!("{base}/contents/{content_hash}")) {
                        return Ok(b);
                    }
                }
                Err(primary_err)
            }
        }
    }

    pub fn fetch_entity(&self, entity_id: &str) -> Result<Scene> {
        let raw = self.fetch_content(entity_id)?;
        let mut v: serde_json::Value = serde_json::from_slice(&raw)
            .map_err(|e| anyhow!("entity {entity_id} is not JSON: {e}"))?;
        ensure_entity_id(&mut v, entity_id);
        Self::parse_entity(&v)
    }

    pub fn base_url(&self) -> &str {
        &self.base
    }

    pub fn active_entities_by_hash(&self, hash: &str) -> Result<Vec<String>> {
        let raw = match self.get(&format!("/contents/{hash}/active-entities")) {
            Ok(b) => b,
            Err(e) => {
                if e.to_string().starts_with("404 ") {
                    return Ok(Vec::new());
                }
                return Err(e);
            }
        };
        let v: serde_json::Value = serde_json::from_slice(&raw)?;
        let arr = v
            .as_array()
            .ok_or_else(|| anyhow!("active-entities did not return an array"))?;
        Ok(arr
            .iter()
            .filter_map(|e| e.as_str().map(str::to_string))
            .collect())
    }

    pub fn parse_entity(ent: &serde_json::Value) -> Result<Scene> {
        let entity_id = ent
            .get("id")
            .and_then(|v| v.as_str())
            .ok_or_else(|| anyhow!("entity has no id"))?
            .to_string();
        let entity_type = ent
            .get("type")
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_string();
        let pointers = ent
            .get("pointers")
            .and_then(|v| v.as_array())
            .map(|a| {
                a.iter()
                    .filter_map(|p| p.as_str().map(|s| s.to_string()))
                    .collect()
            })
            .unwrap_or_default();
        let content = ent
            .get("content")
            .and_then(|v| v.as_array())
            .map(|a| {
                a.iter()
                    .filter_map(|c| {
                        let file = c.get("file")?.as_str()?.to_string();
                        let hash = c.get("hash")?.as_str()?.to_string();
                        Some(ContentEntry { file, hash })
                    })
                    .collect()
            })
            .unwrap_or_default();
        let metadata = ent
            .get("metadata")
            .cloned()
            .unwrap_or_else(|| serde_json::json!({}));
        Ok(Scene {
            entity_id,
            entity_type,
            pointers,
            content,
            metadata,
        })
    }

    pub fn fetch_active_entity_by_id(&self, entity_id: &str) -> Result<Scene> {
        let body = serde_json::json!({ "ids": [entity_id] });
        let raw = self.post_json("/entities/active", &body)?;
        let arr: serde_json::Value = serde_json::from_slice(&raw)?;
        let arr = arr
            .as_array()
            .ok_or_else(|| anyhow!("entities/active did not return an array"))?;
        match arr.first() {
            Some(e) => Self::parse_entity(e),
            None => bail!(
                "no active entity matched id {entity_id} on {} \
                 (likely a content CID or a stale/redeployed scene entity)",
                self.base
            ),
        }
    }

    pub fn resolve_entities(&self, pointers: &[String]) -> Result<Vec<Scene>> {
        if pointers.is_empty() {
            return Ok(Vec::new());
        }
        let body = serde_json::json!({ "pointers": pointers });
        let raw = self.post_json("/entities/active", &body)?;
        let arr: serde_json::Value = serde_json::from_slice(&raw)?;
        let arr = arr
            .as_array()
            .ok_or_else(|| anyhow!("entities/active did not return an array"))?;
        arr.iter().map(Self::parse_entity).collect()
    }

    pub fn collection_member_urns(
        &self,
        lambdas_base: &str,
        collection_id: &str,
    ) -> Result<Vec<String>> {
        let lambdas = lambdas_base.trim_end_matches('/');
        let url = format!("{lambdas}/collections/wearables?collectionId={collection_id}");
        let mut last: Option<String> = None;
        let raw: Option<Vec<u8>> = (|| {
            for attempt in 0..HTTP_RETRIES {
                match self.agent.get(&url).header("User-Agent", UA).call() {
                    Ok(resp) => {
                        let mut buf: Vec<u8> = Vec::new();
                        if let Err(e) = resp.into_body().into_reader().read_to_end(&mut buf) {
                            last = Some(e.to_string());
                        } else {
                            return Some(buf);
                        }
                    }
                    Err(ureq::Error::StatusCode(code)) => {
                        last = Some(format!("HTTP {code}"));
                        if code == 404 {
                            return None;
                        }
                    }
                    Err(e) => last = Some(e.to_string()),
                }
                std::thread::sleep(backoff(attempt));
            }
            None
        })();
        let raw = raw.ok_or_else(|| anyhow!("GET {} failed: {}", url, last.unwrap_or_default()))?;
        let doc: serde_json::Value = serde_json::from_slice(&raw)?;
        let wearables = doc
            .get("wearables")
            .and_then(|v| v.as_array())
            .ok_or_else(|| anyhow!("collection response had no 'wearables' array"))?;
        let urns: Vec<String> = wearables
            .iter()
            .filter_map(|w| w.get("id").and_then(|v| v.as_str()).map(|s| s.to_string()))
            .collect();
        Ok(urns)
    }

    pub fn resolve_scene(&self, target: &str) -> Result<Scene> {
        let ent: serde_json::Value = if is_pointer(target) {
            let body = serde_json::json!({ "pointers": [target.trim()] });
            let raw = self.post_json("/entities/active", &body)?;
            let arr: serde_json::Value = serde_json::from_slice(&raw)?;
            let arr = arr
                .as_array()
                .ok_or_else(|| anyhow!("entities/active did not return an array"))?;
            if arr.is_empty() {
                bail!("no active entity at pointer {:?}", target);
            }
            arr[0].clone()
        } else {
            let raw = self.fetch_content(target)?;
            let mut ent: serde_json::Value = serde_json::from_slice(&raw)?;
            ensure_entity_id(&mut ent, target);
            ent
        };

        Self::parse_entity(&ent)
    }
}

use std::io::Read;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pointer_detection() {
        assert!(is_pointer("-9,-9"));
        assert!(is_pointer("0,0"));
        assert!(is_pointer(" 12,-34 "));
        assert!(is_pointer("100,200"));
        assert!(!is_pointer("abc"));
        assert!(!is_pointer("1,2,3"));
        assert!(!is_pointer("1.5,2"));
        assert!(!is_pointer("Qm..."));
        assert!(!is_pointer(",5"));
    }

    #[test]
    fn content_helpers() {
        let s = Scene {
            entity_id: "e".into(),
            entity_type: String::new(),
            pointers: vec![],
            content: vec![
                ContentEntry {
                    file: "Models/A.GLB".into(),
                    hash: "h1".into(),
                },
                ContentEntry {
                    file: "tex/b.png".into(),
                    hash: "h2".into(),
                },
            ],
            metadata: serde_json::json!({}),
        };
        let map = s.content_by_file();
        assert_eq!(map.get("models/a.glb").map(String::as_str), Some("h1"));
        let glbs = s.files_with_ext(&[".glb"]);
        assert_eq!(glbs.len(), 1);
        assert_eq!(glbs[0].hash, "h1");
    }

    fn scene_with(files: &[(&str, &str)], metadata: serde_json::Value) -> Scene {
        Scene {
            entity_id: "e".into(),
            entity_type: "scene".into(),
            pointers: vec![],
            content: files
                .iter()
                .map(|(file, hash)| ContentEntry {
                    file: (*file).into(),
                    hash: (*hash).into(),
                })
                .collect(),
            metadata,
        }
    }

    #[test]
    fn genesis_plaza_metadata_only_set() {
        let s = scene_with(
            &[
                (
                    "assets/models/pool/autogenerated-thumbnail.png",
                    "bafybeiatkw3bx7ja5corzipqe64xsaavaj37o2lfvt6iiiwag5ezxuqyca",
                ),
                (
                    "assets/models/pool/GPthumb.png",
                    "bafybeihjx4ugiye3ruqfcv54tu5p5keuy3x2l2u2o5otfczlb6dfp734bq",
                ),
                (
                    "assets/models/pool/Aisha.glb",
                    "bafybeiclzteqcssvtk54mmxhtdqo75rueoh5m4qqlhadfgq6wdt3zkfopa",
                ),
                (
                    "assets/models/pool/atlas_1024.png",
                    "bafybeiey34htvdlsyo2ncrid4ayieyfrytphg7by2lgssd72bocgm3cl4y",
                ),
            ],
            serde_json::json!({"display": {"navmapThumbnail": "assets/models/pool/GPthumb.png"}}),
        );
        let mut got: Vec<String> = s.metadata_only_hashes().into_iter().collect();
        got.sort();
        assert_eq!(
            got,
            vec![
                "bafybeiatkw3bx7ja5corzipqe64xsaavaj37o2lfvt6iiiwag5ezxuqyca".to_string(),
                "bafybeihjx4ugiye3ruqfcv54tu5p5keuy3x2l2u2o5otfczlb6dfp734bq".to_string(),
            ]
        );
    }

    #[test]
    fn metadata_only_matches_upstream_classification_rules() {
        let none = scene_with(&[("tex/a.png", "h1")], serde_json::json!({}));
        assert!(none.metadata_only_hashes().is_empty());

        let root_thumb = scene_with(
            &[("autogenerated-thumbnail.png", "h1")],
            serde_json::json!({}),
        );
        assert_eq!(root_thumb.metadata_only_hashes().len(), 1);

        let cased = scene_with(
            &[("Assets/AutoGenerated-Thumbnail.PNG", "h1")],
            serde_json::json!({}),
        );
        assert_eq!(cased.metadata_only_hashes().len(), 1);

        let lookalike = scene_with(
            &[
                ("assets/my-autogenerated-thumbnail.png", "h1"),
                ("assets/autogenerated-thumbnail.png.bak", "h2"),
            ],
            serde_json::json!({}),
        );
        assert!(lookalike.metadata_only_hashes().is_empty());

        let navmap_cased = scene_with(
            &[("Assets/Thumb.png", "h1")],
            serde_json::json!({"display": {"navmapThumbnail": "assets/thumb.PNG"}}),
        );
        assert_eq!(
            navmap_cased.metadata_only_hashes().into_iter().next(),
            Some("h1".to_string())
        );

        let dangling = scene_with(
            &[("tex/a.png", "h1")],
            serde_json::json!({"display": {"navmapThumbnail": "missing.png"}}),
        );
        assert!(dangling.metadata_only_hashes().is_empty());

        let non_string = scene_with(
            &[("tex/a.png", "h1")],
            serde_json::json!({"display": {"navmapThumbnail": 7}}),
        );
        assert!(non_string.metadata_only_hashes().is_empty());

        let no_display = scene_with(&[("tex/a.png", "h1")], serde_json::json!({"display": "x"}));
        assert!(no_display.metadata_only_hashes().is_empty());
    }
}
