/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** One content file. `name` is the entity's content path. */
export interface AbgenFile {
  name: string
  data: Buffer
}
export interface AbgenContentEntry {
  file: string
  hash: string
}
/** One produced bundle, named `<hash>_<deps>_<platform>`. */
export interface AbgenBundle {
  name: string
  data: Buffer
}
/** A conversion job. */
export interface AbgenConvertOptions {
  files: Array<AbgenFile>
  /** `"windows"` (default), `"mac"`, `"linux"` or `"webgl"`. */
  platform?: string
  /** Omit to detect from the files. */
  entityType?: string
  /** 0 convert (default), 1 scan, 2 convert one model, 3 LOD only. */
  mode?: number
  magentaMissing?: boolean
  bakeLod?: boolean
  crop?: boolean
  /** 0 leaves the LOD uncapped. */
  triangleCap?: number
  /** Names the LOD (mode 3). Omit to derive from the content table. */
  entityHash?: string
  /** In mode 2, which file to convert. */
  onlyGlb?: string
  /**
   * The entity's full table, so cross-file dependency hashes resolve even
   * when `files` carries only a shard.
   */
  contentTable?: Array<AbgenContentEntry>
}
/** Everything one conversion produced. */
export interface AbgenConvertResult {
  /** 0 on success; 1 malformed request; 2 conversion failed. */
  code: number
  bundles: Array<AbgenBundle>
  /** Raw JSON progress events, in order. */
  events: Array<string>
  errors: Array<string>
  manifest?: string
}
export declare function version(): string
/**
 * Converts one entity on the blocking pool, not the libuv event loop:
 * conversion is CPU-bound for seconds at a time.
 *
 * A model that fails is **not** a rejected promise — it comes back as a
 * `file-error` in `events` and a non-zero `exitCode` in `manifest`, `code`
 * still 0.
 */
export declare function convert(options: AbgenConvertOptions): Promise<AbgenConvertResult>
